obelisk/plaid

- Cargo.lock
- Cargo.toml
- plaid-stl/Cargo.lock
- plaid-stl/Cargo.toml
- plaid-stl/src/github/mod.rs
- plaid/Cargo.toml
- plaid/resources/Cargo.toml
- plaid/resources/Dockerfile_quorum.aarch64
- plaid/resources/plaid.toml
- plaid/src/apis/github/graphql.rs
- plaid/src/apis/github/mod.rs
- plaid/src/apis/github/pats.rs
- plaid/src/apis/github/repos.rs
- plaid/src/apis/github/teams.rs
- plaid/src/apis/github/validators.rs
- plaid/src/apis/mod.rs
- plaid/src/config.rs
- plaid/src/functions/api.rs
- plaid/src/loader/mod.rs
- plaid/src/main.rs
- plaid/src/storage/sled/mod.rs
There are some APIs that are only available to GitHub apps (FPATs). This adds a new configuration method so that Plaid can make GitHub rest calls as a GitHub app to access these APIs.
We continue to support the only PAT configuration method but App specific APIs will fail if used.
> Update GH Subsystem To Support GitHub Apps

- plaid/resources/plaid.toml
- plaid/src/apis/general/mod.rs
- plaid/src/apis/mod.rs
- plaid/src/apis/okta/mod.rs
- plaid/src/apis/pagerduty/mod.rs
- plaid/src/apis/slack/mod.rs
- plaid/src/apis/splunk/mod.rs
- plaid/src/apis/yubikey/mod.rs
- plaid/src/data/okta/mod.rs
This PR fixes the current issues with the Okta data generator and implements additional customizability to the generator.
The generator was failing due to an issue in the URI string where the date provided did not match the requirements set by the Okta `/log` API. To address this, we convert the timestamp to RFC3339 before sending the request.
We also add additional configuration values for the generator in the form of `limit` and `sleep_duration`. `limit` is passed as a query param to the API to limit the number of logs returned from Okta. If no value is provided, we use Okta's default of 100. `sleep_duration` is intended to mitigate any possibility of getting rate limited by Okta. The `/logs` endpoint restricts us to 50 calls/minute and consequently, it's rate limiting is likely. After …
> Okta tailer 

- Cargo.lock
- plaid-stl/Cargo.toml
- plaid/Cargo.toml
- plaid/resources/Cargo.toml
- plaid/resources/Dockerfile.aarch64
- plaid/resources/Dockerfile.amd64
- plaid/resources/plaid.toml
- plaid/resources/secrets.example.json
- plaid/src/config.rs
- plaid/src/loader/errors.rs
- plaid/src/loader/mod.rs
- plaid/src/loader/utils.rs
- plaid/src/main.rs
This PR implements a mechanism to interpolate secrets Plaid's config at runtime. We read the config in as a string, read the secrets in as a `Map<String, serde_json::Value>` and replace all occurrences of `String` with its corresponding value in the provided secrets file.
Example:
With a secrets file like: 
```json
{
"{plaid-secret{test-secret}}": "This is a test secret",
}
```
and a config like:
```toml
[loading.secrets]
[loading.secrets."testing"]
"test_secret" = "{plaid-secret{test-secret}}"
```
We're able to run a simple rule that parrots our secret back to us:
```
[2024-07-12T16:42:49Z INFO  plaid] Plaid is booting up, please standby...
[2024-07-12T16:42:49Z INFO  plaid] Reading configuration
[2024-07-12T16:42:49Z INFO  plaid] Reading secrets file at …
```
> Move config secrets

- Cargo.lock
- plaid-stl/src/messages.rs
- plaid/Cargo.toml
- plaid/resources/plaid.toml
- plaid/src/bin/plaid.rs
- plaid/src/data/mod.rs
- plaid/src/data/websocket/mod.rs
- plaid/src/data/websocket/selector.rs
- plaid/src/logging/mod.rs
- plaid/src/logging/stdout.rs
This PR implements WebSocket data generators to Plaid. 
The `websocket` module defines an optional `WebsocketDataGenerator` configuration struct that takes map of generator names to socket configuration. This allows us to give names to the generators that will later by passed to rules.
In the example configuration below, we define a generator named `demo_rpc_call`. Its fields are:
- `uris`: A list of URIs that can generate data. We allow for many URIs to add resiliency in the case that a socket becomes disconnected. The generator implements a round-robin strategy with exponential backoff to retry connections to sockets on failure.
- There are two additional fields for further customization of the retry strategy: (1) `min_retry_duration` and (2) `max_retry_duration`. As their names …
> Implement WebSocket data generator

- plaid-stl/src/aws/kms.rs
- plaid/Cargo.toml
- plaid/src/apis/aws/kms.rs
- plaid/src/functions/api.rs
Addresses bugs I've run into when trying to write a rule using the new KMS APIs.
Passing the message from KMS to sign as a `String` was silly of me - have made that a `Vec<u8>` now which allows us to do away with the `parse_message` function. 
I also ran into issues using API key auth with short lived credentials to AWS as I was missing a session token. We now allow for an optional session token in the `Authentication` enum.
Finally, I linked the functions incorrectly and have now fixed that
(Also enables AWS by default)
> KMS tweaks

- plaid-stl/src/github/mod.rs
- plaid/resources/plaid.toml
- plaid/src/apis/github/repos.rs
This PR adds support for paginated responses from the GitHub API when fetching a repo's collaborators. See [the docs](https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#list-repository-collaborators) for more details about that endpoint.
The main idea is that we will always make a GET call with query params `page` and `per_page`. If these params are not given, then we default to 1 and 30, respectively (which are the defaults used by GH).
The existing `get_repository_collaborators` in plaid-stl has been marked as deprecated, and `get_all_repository_collaborators` has been added.
The changes are backwards compatible because
* In the plaid-stl we only add `get_all_repository_collaborators`
* In the plaid API, we expect extra parameters `page` and `per_page`, …
> Support paginated responses for GH get_repository_collaborators

- plaid-stl/src/github/mod.rs
- plaid/src/apis/github/repos.rs
- plaid/src/functions/api.rs
This PR adds API functionality to fetch the files in a PR. Both the `list_files` and `fetch_file` methods are implemented and the API has also been implemented in plaid-stl.
Note that the path of the file is currently not validated, as the raw string representation of a path is formatted in HTML. If needed, I can add a validator for the path.
> Add github API methods to fetch files in a Pull Request

- plaid/resources/generate_jwks_for_okta.py
This PR adds a script that allows one to generate JWKS for authenticating Plaid as an Okta app to the Okta service.
More details in the script's comments.
> Add script for generating Okta auth keys

- Cargo.lock
- plaid-stl/Cargo.toml
- plaid-stl/src/lib.rs
- plaid-stl/src/npm/mod.rs
- plaid-stl/src/npm/shared_structs/mod.rs
- plaid/Cargo.toml
- plaid/src/apis/general/random.rs
- plaid/src/apis/mod.rs
- plaid/src/apis/npm/hashes.rs
- plaid/src/apis/npm/mod.rs
- plaid/src/apis/npm/npm_cli_client.rs
- plaid/src/apis/npm/npm_web_client.rs
- plaid/src/apis/npm/validators.rs
- plaid/src/functions/api.rs
1. Publish empty package stub
2. Invite user to organization
3. Remove user from organization
4. Add user to team
5. Remove user from team
6. Get list of users in the organization
7. Get list of users in the organization without 2FA enabled
8. Set team permissions on a package
9. Create granular token for package
10. List all granular tokens (with expiration date)
11. Delete a package (TBC if we want to expose this)
12. List packages over which a team has certain permissions (useful to spot misconfigured packages)
* Shared structs are all defined in the STL, since `plaid` depends on `plaid-stl`. Therefore, the code can serialize and deserialize using the same types across the host/guest boundary.
* The TOTP functionality is embedded in the code that uses it. TBD if we want to separate it …
> Add npm API to Plaid

- Cargo.lock
- plaid-stl/src/github/mod.rs
- plaid/Cargo.toml
- plaid/resources/plaid.toml
- plaid/src/apis/github/environments.rs
- plaid/src/apis/github/mod.rs
- plaid/src/apis/github/secrets.rs
- plaid/src/apis/github/validators.rs
- plaid/src/functions/api.rs
We expose STL methods to
* Create a GH environment for a given repository, setting up a deployment protection rule that targets a given branch
* Configure a secret on a GH environment. The secret is passed in plaintext and encrypted in the plaid runtime before being sent to GitHub's API
None
> Support creating a GH environment with protection rules and env secret

- Cargo.lock
- plaid-stl/Cargo.toml
- plaid/Cargo.toml
- plaid/resources/Cargo.toml
Mostly this just fixes the build for Linux containers where SSL couldn't be found when linking (because it wasn't there) but it also officially sets the version to 13 now that NPM and new GitHub APIs have been merged.
> Fix SSL On Linux; Cut Next Major Version

- plaid-stl/src/npm/mod.rs
- plaid-stl/src/npm/shared_structs/mod.rs
- plaid/src/apis/npm/npm_cli_client.rs
- plaid/src/apis/npm/npm_web_client.rs
- plaid/src/apis/npm/validators.rs
- plaid/src/functions/api.rs
Instead of taking a single package name, take a vector of package names. They are all validated and used to define the scope of the token.
Also allow callers to specify the GH repo linked to the package, instead of assuming it is the same as package_name.
> [npm] Support creating tokens for multiple packages at once

- plaid/src/bin/plaid.rs
- plaid/src/executor/mod.rs
- plaid/src/loader/mod.rs
This PR adds a mechanism to mark rules that cannot be processed in parallel. In the configuration we can define single threaded rules like so:
```toml
[loading]
single_threaded_rules = ["testing_test.wasm"]
```
When one of these rules is seen in the execution loop, we check a list of "in flight" rules to see if it's already being processed. If it is, the message is sent back into the log queue for processing. If it's not, we add the rule name to the list of in flight rules and continue with execution. When execution is finished, we remove the rule from the in flight list.
> Add mechanism to process modules non concurrently

- plaid-stl/src/npm/mod.rs
- plaid-stl/src/npm/shared_structs/mod.rs
- plaid/src/apis/npm/mod.rs
- plaid/src/apis/npm/npm_web_client.rs
- plaid/src/apis/npm/validators.rs
- plaid/src/functions/api.rs
This PR adds
* An API to retrieve some details about an npm granular token (including the packages it can publish). Further processing is left to the calling rule.
* An API to delete npm granular tokens
* An API to renew an npm granular token "in place", i.e., overwrite it with a token that has the same name and same publish scope
> Add npm APIs for retrieving details about / deleting / renewing a granular token

- plaid-stl/src/github/mod.rs
- plaid/src/apis/github/copilot.rs
- plaid/src/apis/github/mod.rs
- plaid/src/apis/github/repos.rs
- plaid/src/apis/github/teams.rs
- plaid/src/functions/api.rs
- Add 3 Github APIs to manage Copilot membership: list, add and remove.
> Add Github API to manage Copilot membership

- plaid/src/apis/npm/npm_web_client.rs
Since the STL supports automatically renewing tokens, tokens can be rotated more frequently without disruption.
We now choose a default duration of 30 days. Rules can still override this value, if they decide to pass detailed token specs.
> Shorten default npm token expiration to 30 days

- plaid/src/apis/npm/npm_web_client.rs
The problem is that `Value`s are returned in JSON format. This was in turn causing problems downstream.
The temporary solution is for the caller downstream to remove all `"` characters from the result, but this is the permanent fix.
> Fix return value for npm token generation

- plaid-stl/src/github/mod.rs
- plaid/src/apis/github/copilot.rs
- plaid/src/apis/github/mod.rs
- plaid/src/functions/api.rs
Upon a successful Copilot API call, we'll return the response body from Github. This will include the number of modifications (seats removed/seats added).
This will allow the rules to handle cases where the API call returns a success status code but no modification took place due to various reasons like the person already subscribed or already removed.
> Return number of seats changed for Copilot API

- plaid-stl/src/plaid/mod.rs
- plaid/src/functions/api.rs
- plaid/src/functions/internal.rs
This PR adds an API for rules to log back with unlimited budget.
Until now, rules could log back either with 0 budget for further invocations, or with a fixed budget. This would not allow one to implement a use case where something needs to continue forever at regular intervals.
Instead, with this change, a rule that picks up a message with unlimited budget can trigger further invocations with unlimited budget.
The change is backward compatible: existing APIs are left untouched and a new API is added.
Malicious rules could use this feature to try and mount a DOS attack against the runtime, by triggering an endless sequence of log backs. In the future, the problem might be addressed by allowing one to specify which rules are trusted to use this feature.
There is no API for a rule to query …
> Add log_back_unlimited API

- plaid-stl/src/slack/mod.rs
- plaid/src/apis/slack/api.rs
- plaid/src/apis/slack/mod.rs
- plaid/src/functions/api.rs
This PR adds a Slack API call to retrieve a Slack ID from a user's email address. See https://api.slack.com/methods/users.lookupByEmail for more information.
@obelisk Perhaps it would make more sense to return a richer Slack user profile and then let the caller pick only the parts that are needed (i.e., the ID). What do you think?
This is also the first GET request we make to the Slack API, so the client code has been rearranged to allow for this and be easily expandable in the future.
> Add Slack API to retrieve ID from email

- plaid-stl/src/datetime.rs
- plaid-stl/src/github/mod.rs
- plaid-stl/src/lib.rs
- plaid-stl/src/npm/shared_structs/mod.rs
- Parse datetime returned from Copilot API in plaid-stl: I realized the npm module of plaid-stl does parse datetime strings returned from APIs. I think parsing it in the plaid-stl would make it much easier to write rules. Also, I need to add the `created_at` field to handle cases where people literally never used their Copilot membership before.
- Add Copilot function to remove multiple users: Initially I wanted to remove user one by one so we specifically tell if the removal took effect from looking at `seats_cancelled`. But I think we'll just remove multiple users at once and let Github attempts it on a best-effort basis.
> Parse Copilot datetime in plaid-stl and add function to remove multiple Copilot seats

- Cargo.lock
- plaid-stl/src/lib.rs
- plaid-stl/src/plaid/mod.rs
- plaid/src/executor/mod.rs
- plaid/src/functions/api.rs
- plaid/src/functions/internal.rs
- plaid/src/functions/memory.rs
This PR adds the following:
* A way for modules to give the Plaid runtime more context about errors they encounter. This is achieved by setting an error context (a `String`) which is then included in the error returned by the runtime.
* A simple panic hook (see [docs](https://doc.rust-lang.org/std/panic/fn.set_hook.html)) that, when a panic occurs, sets an appropriate context.
Note - The panic hook has been tested and works for things like explicit `panic!` and `index out of bounds`, but does not seem to work for OOM errors. For this reason, the explanation for an unknown error defaults to "This is probably an OOM error", since this is the only case we know of where the hook is not triggered and an explanation is not available.
**! This change forces all rules to be modified and …
> Support adding error context for Plaid runtime + panic hook

- plaid-stl/src/lib.rs
There was a mistake (mine) in the entrypoint, in that the `plaid` import was not there. So the code would rely on the rule (where the macro is actually called) to import `plaid_stl::plaid`. This makes everything self-contained and the rule can just call the macro.
> Make entrypoint self-contained by importing all that is necessary

- plaid-stl/src/github/mod.rs
- plaid/src/apis/github/actions.rs
- plaid/src/apis/github/mod.rs
- plaid/src/apis/github/validators.rs
- plaid/src/functions/api.rs
This PR exposes a new API `trigger_repo_dispatch` through which a rule can trigger a GHA workflow via `repository_dispatch` on a given repository.
> Add support for triggering GHA via repository_dispatch

- Cargo.lock
- plaid/Cargo.toml
Following https://crates.io/crates/jwt-simple#working-around-compilation-issues-with-the-boring-crate we ditch the `boring` dependency and instead use `superboring`.
As mentioned [here](https://crates.io/crates/superboring), using `superboring` helps fixing issues with symbol collisions between `boring` and `libssl`, which we were encountering when building plaid in GH Actions.
> Move to superboring for SSL

- plaid/examples/tailers/github.rs
- plaid/resources/plaid.toml
- plaid/src/apis/github/mod.rs
- plaid/src/data/github/mod.rs
This makes the GitHub data generator compatible with GitHub app creds, removing the need for FPATs as described in [this issue](https://github.com/obelisk/plaid/issues/6)
It could be nice to have the API and data generator share the same GitHub client, but that would require breaking changes to the config to move the authentication settings outside of the API and data generators section.
> Modify GitHub data generator to work with GitHub app credentials

- Cargo.lock
- plaid/Cargo.toml
- plaid/src/apis/npm/mod.rs
- plaid/src/apis/npm/npm_web_client.rs
- plaid/src/bin/plaid.rs
This PR fixes a problem where requests to the npm website would fail when the runtime has been spinning for a while.
The root cause is (most likely) cookies expiring. This PR does the following:
* Use a more advanced cookie provider for the `reqwest` client. This provider exposes a richer API that, among other things, allows us to clear cookies.
* Clear cookies if the previous call had been made more than 2 minutes earlier, which will trigger a new login. This is acceptable because
* A full login takes ~3 seconds
* It still fulfills the basic purpose: if a rule makes more than one request one after the other, then only one login is made
* It fixes the problem described above
> [npm] Improve management of cookies and login

- .gitignore
- runtime/Cargo.lock
- runtime/plaid-stl/src/lib.rs
- runtime/plaid/Cargo.toml
- runtime/plaid/resources/plaid.toml
- runtime/plaid/src/benchmark/mod.rs
- runtime/plaid/src/bin/plaid.rs
- runtime/plaid/src/config.rs
- runtime/plaid/src/executor/mod.rs
- runtime/plaid/src/functions/api.rs
- runtime/plaid/src/functions/message.rs
- runtime/plaid/src/lib.rs
- runtime/plaid/src/performance/mod.rs
Currently, we're unable to quantify how subtle changes to a rule or the Plaid runtime affect performance. This PR implements a mechanism to benchmark and compare Plaid rules, enabling developers and plaidmins to maximize their instance's performance. When enabled, it logs rule execution metadata (rule name, execution time, computation used) to a task that aggregates this data based on rule name. On shutdown, the benchmarking system writes this data out to a file.
Triggering shutdown of the server is done with `CTRL+C` or by sending a `SIGTERM` signal. Plaid is configured to listen for this signal and begin a graceful shutdown. Right now, graceful shutdown means waiting for the `benchmark_loop` task to exit. This allows us to guarantee that our benchmarking data will be written to a file …
> Implement benchmarking system

- runtime/plaid-stl/src/github/mod.rs
- runtime/plaid/src/apis/github/repos.rs
- runtime/plaid/src/functions/api.rs
When checking if a repository's protection is correctly configured, we need to check if the default branch is protected by either
* the "traditional" BPRs
* the "new" rules (organized in rulesets)
This PR adds runtime support for fetching the "new" protection rules.
> [GH] Add support for fetching new protection rules

- runtime/plaid-stl/src/github/mod.rs
- runtime/plaid/src/apis/github/repos.rs
- runtime/plaid/src/apis/github/validators.rs
The `fetch_file` API required a commit hash for the `ref` parameter. In cases where we need to fetch a file from a branch, this is too restrictive. This PR modifies the parameter validation for `ref` to check that it is either a valid commit hash OR branch name. It also adds an additional check to `file_path` to validate that it does not contain `..`
It also adds some formatting changes (not on purpose but we can blame my formatter). However, this is a great plug for https://github.com/obelisk/plaid/pull/58 as it means we won't run into scenarios where code gets changed because of formatting
> Add documentation for GH fetch files + modify parameter validation

- .github/workflows/ConfigChecker.yaml
Adds a GHA workflow to release the config check binary as an artifact. This can then be used by other repositories to quickly validate a set of Plaid configs.
> Release config checker binary as an artifact

- modules/tests/test_db/harness/harness.sh
- modules/tests/test_db/src/lib.rs
- runtime/plaid-stl/src/plaid/storage.rs
- runtime/plaid/resources/plaid.toml
- runtime/plaid/src/functions/api.rs
- runtime/plaid/src/functions/storage.rs
Rules can now call `plaid::storage::delete(...)` to delete a key in their namespace.
Also refactored the test for DB functionality.
> Add STL function to delete keys from Plaid DB

- .github/workflows/ConfigChecker.yaml
The GH action to create a release needs extra permissions.
> Fix config checker release

- runtime/plaid/src/apis/npm/npm_web_client.rs
This missing header was causing npm to respond with a 404. The reason is unknown, but it is a pattern we have already encountered, so trying to add `X-Spiferack: 1` is usually a good starting point.
> Set X-Spiferack header

- modules/Cargo.lock
- modules/tests/test_db/harness/harness.sh
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid-stl/src/messages.rs
- runtime/plaid/Cargo.toml
- runtime/plaid/resources/plaid.toml
- runtime/plaid/src/bin/plaid.rs
- runtime/plaid/src/executor/mod.rs
- runtime/plaid/src/functions/api.rs
- runtime/plaid/src/functions/cache.rs
- runtime/plaid/src/functions/internal.rs
- runtime/plaid/src/functions/message.rs
- runtime/plaid/src/functions/mod.rs
- runtime/plaid/src/functions/response.rs
- runtime/plaid/src/functions/storage.rs
- runtime/plaid/src/loader/mod.rs
- runtime/plaid/src/loader/utils.rs
- runtime/plaid/src/storage/mod.rs
- runtime/plaid/src/storage/sled/mod.rs
This PR adds an optional size limit that modules must respect when storing data in the permanent storage (e.g., DB).
If a module tries to store more than it is allowed, the insertion will fail.
Modules can also be given (by default or through overrides) `Unlimited` storage in the DB, in which case we will still count how many bytes they are storing, but we will not fail the insert.
When counting what is stored, we take into account the byte length of the key and the values.
The configuration needs a new section that looks like
```
[loading.storage_size]
default = "Unlimited"
[loading.storage_size.log_type]
[loading.storage_size.module_overrides]
"test_db.wasm" = { Limited = 50 }
```
> Add size limit for storing in the DB

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid/Cargo.toml
- runtime/plaid/src/apis/npm/npm_web_client.rs
Without this header, the call "works" in the sense that the invite is sent out, but the status code is not 200 and that's seen as an error.
> [npm] Add X-Spiferack header when inviting user to org

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid/Cargo.toml
- runtime/plaid/src/data/okta/mod.rs
Okta DG could enter a deadlock if we get more than 100 logs in one minute. More detailed explanation in the comment to the fix.
> Fix bug in Okta DG

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid-stl/src/github/mod.rs
- runtime/plaid/Cargo.toml
1 MiB is easily filled with large-ish GitHub commits, so we bump the buffer size to 5 MiB.
> Use a larger buffer when fetching commits from GitHub

- modules/Cargo.lock
- modules/Cargo.toml
- modules/tests/test_shared_db_rule_1/Cargo.toml
- modules/tests/test_shared_db_rule_1/harness/harness.sh
- modules/tests/test_shared_db_rule_1/src/lib.rs
- modules/tests/test_shared_db_rule_2/Cargo.toml
- modules/tests/test_shared_db_rule_2/src/lib.rs
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid-stl/src/plaid/storage.rs
- runtime/plaid/Cargo.toml
- runtime/plaid/resources/plaid.toml
- runtime/plaid/src/bin/plaid.rs
- runtime/plaid/src/functions/api.rs
- runtime/plaid/src/functions/mod.rs
- runtime/plaid/src/functions/storage.rs
- runtime/plaid/src/loader/utils.rs
- runtime/plaid/src/storage/mod.rs
Sometimes it makes sense for rules to share a common database, so that data written by a rule can be read by another one. For example, this can remove the need for log-backs in case we need to pass information from rule A to rule B and the synchronization is already handled somewhere else.
This PR introduces support for shared DBs in a fully backward-compatible way. We add new APIs like `insert_shared`, `get_shared`, `delete_shared` that also take a namespace, which represents the shared DB.
Moreover, at the config level, we can specify which rules have read-only access and which rules can read/write.
Note: write-only is not currently supported because a write op inherently requires a read op to fetch existing data under the same key. This could change in the future.
> Support DBs shared between rules

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid-stl/src/github/mod.rs
- runtime/plaid/Cargo.toml
- runtime/plaid/src/apis/github/deploy_keys.rs
- runtime/plaid/src/apis/github/mod.rs
- runtime/plaid/src/functions/api.rs
Add runtime API to delete GH deploy keys. The API requires the caller to specify the repo owner, the repo name, and the deploy key's ID.
> Add runtime API to delete GH deploy keys

- runtime/plaid/examples/tailers/github.rs
- runtime/plaid/src/data/github/mod.rs
- runtime/plaid/src/data/mod.rs
- runtime/plaid/src/data/okta/mod.rs
This PR unifies the logic for data generators (Okta and GitHub).
The basic idea is that each of Okta and GitHub DG implement a specific logic to fetch some logs from the respective API that were created in a given time window (since...until).
Then there is higher-level logic to take these logs and process them, discarding duplicates, etc. This logic is common between Okta and GH.
Commonalities are expressed through a `DataGenerator` trait which both sources implement. Methods from this trait are then called from the high-level logic to perform all necessary operations.
> Unify data generators for GH and Okta

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid-stl/src/github/mod.rs
- runtime/plaid/Cargo.toml
- runtime/plaid/src/apis/github/code.rs
- runtime/plaid/src/apis/github/validators.rs
- runtime/plaid/src/functions/api.rs
Improve the API for search code on GH, supporting searches target to a filename, an extension, and/or a path.
This is a breaking change
@obelisk Let's bump the version depending on the order in which we merge PRs.
> Improve the API for search code on GH

- .github/workflows/Release.yaml
- modules/Cargo.lock
- modules/tests/test_db/harness/harness.sh
- modules/tests/test_db/src/lib.rs
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid/Cargo.toml
- runtime/plaid/resources/plaid.toml
- runtime/plaid/src/apis/aws/kms.rs
- runtime/plaid/src/bin/plaid.rs
- runtime/plaid/src/executor/mod.rs
- runtime/plaid/src/functions/api.rs
- runtime/plaid/src/functions/storage.rs
- runtime/plaid/src/lib.rs
- runtime/plaid/src/storage/dynamodb/mod.rs
- runtime/plaid/src/storage/mod.rs
- runtime/plaid/src/storage/sled/mod.rs
- testing/integration.sh
This PR adds support for AWS DynamoDB as Plaid's DB layer.
Some points to note:
* DynamoDB is very fast but still slower than a local DB on file. This is why we had to add `sleep ...` in the DB test, which would otherwise fail for ~unclear reasons. To be investigated more thoroughly, but this is likely due to network latency or consistency.~ reasons explained in the comment below.
* The mechanism to authenticate to AWS (either via API key or IAM role) has been refactored out of the KMS submodule, since it's generic enough to be reused. This does not prevent KMS and DynamoDB from using different authentications.
* We could consider gating DynamoDB support behind a feature with optional dependencies.
* ~There is a TODO in the code for further consideration. When fetching all the keys, we …
> Support AWS DynamoDB for Plaid DB

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid/Cargo.toml
- runtime/plaid/src/bin/secrets_manager.rs
For multi-tenant deployments, where multiple Plaid instances are deployed on the same AWS account, it's important to distinguish secrets that belong to one deployment from the others. AWS Secrets Manager does not support the notion of "buckets" or "folders", so we use a name prefix as a way to segment secrets. This PR adds an item to the prefix: `deployment`.
Plaid secrets in AWS Secrets Manager will be called `plaid-<deployment>-<instance>-<secret_name>`. This way we can have
* `plaid-first_deployment-plaid-my_secret`
* `plaid-second_deployment-plaid-my_secret`
* `plaid-first_deployment-ingress-my_secret`
* `plaid-second_deployment-ingress-my_secret`
with no conflicts.
@obelisk It requires cutting a new release, so that we appropriately publish a new version of the secrets manager …
> Add deployment name to AWS SM secret names

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid/Cargo.toml
- runtime/plaid/src/bin/plaid.rs
- runtime/plaid/src/executor/mod.rs
- runtime/plaid/src/functions/message.rs
A [recent change](https://github.com/obelisk/plaid/pull/74) modified the structure of a `Message`, introducing fields for `headers` and `query_params` of type `HashMap<_, _>` in place of the old `accessory_data`.
However, a running system will likely have logbacks in its DB. Logbacks produced before that refactor are no longer deserializable because they follow the old structure.
Plaid logs will show something like this
```
Skipping log in storage system which could not be deserialized [missing field `headers` at line 1 column 588]: \"{\\\"type_\\\":\\\"***\\\",\\\"data\\\":[***],\\\"accessory_data\\\":{},\\\"module\\\":\\\"***\\\"}\"
```
Notice how it still shows the old `accessory_data`.
Change the `Message` struct so that `headers` and `query_params` are `Option<HashMap<_, _>>`.
This …
> Fix deserialization of old logbacks

- .gitignore
- runtime/Cargo.lock
- runtime/plaid/Cargo.toml
- runtime/plaid/resources/plaid.toml
- runtime/plaid/resources/secrets.example.json
- runtime/plaid/src/loader/errors.rs
- runtime/plaid/src/loader/mod.rs
- runtime/plaid/src/loader/signing.rs
- runtime/plaid/src/loader/utils.rs
- testing/integration.sh
The PR implements a mechanism to require that rules be signed prior to loading them. In `plaid.toml` this looks like:
```toml
[loading.rule_signing]
authorized_signers = [""]
signature_namespace = "SomeNamespace"
signature_dir = "/path/to/signatures"
```
When `[loading.rule_signing]` is present in `plaid.toml`, we require that ALL rules are signed by an authorized signer. This all or nothing approach greatly simplifies rule signing. When rule signing is enabled, the loading system:
1. Fetches the rule's signature from `signature_dir`
2. Validates the signature and checks that it was produced by one of `authorized_signers`
3. Computes the hash of the rule
4. Validates the signature against the rule's hash
This PR is as much a process change in Plaid administration as it is a code change. …
> Implement module signing

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid/Cargo.toml
- runtime/plaid/src/bin/db_migrator.rs
- runtime/plaid/src/bin/plaid.rs
- runtime/plaid/src/data/internal/mod.rs
- runtime/plaid/src/data/mod.rs
- runtime/plaid/src/executor/mod.rs
- runtime/plaid/src/functions/message.rs
- runtime/plaid/src/storage/dynamodb/mod.rs
- runtime/plaid/src/storage/mod.rs
- runtime/plaid/src/storage/sled/mod.rs
Main changes:
* Every `Message` now has an ID. This is immediately useful for logbacks, and can be useful for other messages too in the future.
* When persisting logbacks in the DB, we use the `Message`'s ID as key, while the value is the serialization of the corresponding `DelayedMessage`.
* When deserializing and deleting logbacks from the DB, we only deserialize the new format. If data exists in the DB that was serialized in the old way(s), then it should be migrated with the tool that this PR introduces.
Note - In the previous format, the key was the JSON serialization of the message, while the value was the byte representation of the logback's delay.
Fixes #12
> Add Message::id and change logbacks' persistence

- runtime/plaid/src/bin/ddb_logback_explorer.rs
Logback explorer:
* Also print the execution delay, i.e., the number of seconds between now and when the logback will be executed
* Allow for filtering based on max delay
* Allow for sorting based on the delay, so that the next logback up for execution is first
> Logback explorer: add delay + sort

- runtime/plaid/src/apis/npm/validators.rs
Something like `aaa.bbb` is a valid NPM username, but the previous validator would consider it invalid because it would not allow the `.` character.
> Allow dot character in npm usernames

- .github/workflows/Integration.yml
- modules/Cargo.lock
- modules/Cargo.toml
- modules/tests/test_slack/Cargo.toml
- modules/tests/test_slack/harness/harness.sh
- modules/tests/test_slack/src/lib.rs
- runtime/plaid-stl/src/slack/mod.rs
- runtime/plaid/resources/plaid.toml
- runtime/plaid/resources/secrets.example.toml
- runtime/plaid/src/apis/slack/api.rs
- runtime/plaid/src/functions/api.rs
- testing/integration.sh
I revisited the Slack API because I wanted to add the ability to fetch user info (specifically timezone data) and I was unhappy with how I previously structured the code. There was no clear separation of responsibilities and it was hard to see how APIs were implemented and especially difficult to add new ones. 
This changes all of that and couples the STL and the Plaid library together to throw compile time errors for inconsistencies rather than runtime `ApiError::MissingParameter` errors.
> Slack API Refactor

- runtime/plaid-stl/src/github/mod.rs
- runtime/plaid/src/apis/github/mod.rs
- runtime/plaid/src/apis/github/pull_requests.rs
- runtime/plaid/src/functions/api.rs
This ads a new GitHub API for requesting reviewers on PRs. Otherwise it's pretty simple but uses the new strict variable passing mechanism of PlaidSTL structs serialized on both ends.
> Add GitHub request reviewers

- runtime/plaid/src/data/github/mod.rs
- runtime/plaid/src/data/okta/mod.rs
Do not log too much information (e.g., the full response body or the full log) when an error occurs in the GitHub or Okta data generators.
> Clean up error logs in data generators

- runtime/plaid/src/data/okta/mod.rs
On a successful call to Okta's `/logs` endpoint, i.e., a call that yields new logs, we now sleep for 1 second before making a new request.
The previous value (1 ms) was not "wrong" but it made it likely for this to happen:
* call `/logs` and get some new logs
* sleep for 1 ms
* call `/logs` and get the same logs (very likely because so little time has passed)
* exit the loop, which will cause the thread to sleep for 10 seconds
With this change, we increase the probability that new logs come in during the sleep time, thus pulling in logs at a more consistent pace.
@wbssbw Unless I am missing something and there was a reason to set that value so low.
> Increase sleep duration when fetching Okta logs

- runtime/plaid/src/bin/db_migrator.rs
- runtime/plaid/src/bin/ddb_logback_explorer.rs
- runtime/plaid/src/storage/dynamodb/mod.rs
- runtime/plaid/src/storage/mod.rs
When using AWS Dynamo DB as the storage layer for Plaid, the table's schema was not validated.
With this PR we make `DynamoDb::new(...)` fallible and return an error if any of the following conditions is not satisfied:
* The table has a partition / hash key called `namespace`
* The table has a sort / range key called `key`
Instead, we do not check the `value` attribute because Dynamo DB supports free attributes, which do not need to be set in advance.
> Add schema validation for Dynamo DB table

- runtime/plaid/src/data/websocket/selector.rs
In `data/websocket/selector.rs` the current logic sleeps only if the `next_attempt` has already passed. This is incorrect and may lead to trying a URI too early
> Update sleep logic in `next_uri()`

- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid-stl/src/github/mod.rs
- runtime/plaid/Cargo.toml
We are exceeding the buffer size limit when querying repo releases. Bumping this buffer size should solve that.
We are only bumping `make_advanced_graphql_query` and not `make_graphql_query` to avoid exceeding the memory limits of rules that are running fine. `make_advanced_graphql_query` is more suitable for bigger responses with the nested response type.
> Bump GraphQL request buffer

- runtime/plaid/resources/config/apis.toml
- runtime/plaid/resources/secrets.example.toml
- runtime/plaid/src/apis/general/mod.rs
- runtime/plaid/src/apis/general/network.rs
- runtime/plaid/src/bin/request_handler.rs
- testing/integration.sh
Previously all MNRs calls shared a single `reqwest::Client`, which made it impossible to tweak timeouts or trust bundles on a per-request basis. This PR introduces a new `Clients` type that holds:  
- A default client for the vast majority of calls.  
- A specialized pool of named clients, each built with its own timeout and/or root TLS certificate when requested.
**What’s Changed**  
- Refactored client-construction logic to scan every request config and spin up a dedicated `Client` if either `timeout` or `root_certificate` is set.
- Consolidated the two modes into a single `Clients` struct, with a `default: Client` and `specialized: HashMap<String, Client>`.
- Ensures that any request requiring extra control (custom timeouts, custom trust chains, etc.) can now use its own tailored HTTP …
> Per-MNR timeout & certificate support

- runtime/plaid/src/bin/secrets_manager/file_to_aws.rs
The `overwrite` flag does not function the way we intend right now. This PR corrects this by first fetching a secret's ARN and then calling `update_secret` to update the value associated with that ARN. If no ARN is found, we'll assume the secret does not exist and create it.
> Fix overwrite mode in secrets manager tool

- modules/Cargo.lock
- runtime/plaid/src/data/github/mod.rs
- runtime/plaid/src/data/mod.rs
- runtime/plaid/src/data/okta/mod.rs
Add support for pagination to `GitHub` and `Okta` data generators. This is done by leveraging the `link` header, which is included by both APIs in a multi-page response.
With this change, we mandate that `fetch_logs` return all logs that happened in the `since..until` time span. If this requires handling pagination, this must be done inside this function.
Note: we also remove the mechanism known as "kicking the window", where we were manually changing `last_seen` to ensure the data generator did not get stuck. The reason is that now we don't limit ourselves to the first page of logs: instead we fetch all the logs in the `since..until` time span. Therefore, as `until` naturally moves forward (since it's calculated as `now - canon_time`) we will automatically get newer logs together with …
> Support pagination in data generators

- runtime/plaid/src/data/interval/mod.rs
The current implementation does not prevent interval jobs from being configured with an interval value of zero.
This can result in jobs that are scheduled to run continuously without any delay, potentially causing a tight loop and
excessive CPU usage.
> Reject interval jobs with zero interval

- runtime/plaid/src/functions/storage.rs
Some of the `*_common()` storage functions returned 0 for error conditions instead of negative error codes, creating ambiguity between success and failure states that could lead to incorrect error handling by WASM modules.
> Storage functions return errors instead of 0

- runtime/plaid-stl/src/github/mod.rs
In `runtime/plaid/src/functions/api.rs` , the API endpoint `update_branch_protection_rule()` is created using the
macro `impl_new_function!`.
However, in `runtime/plaid-stl/src/github/mod.rs` , the endpoint is defined using the macro `new_host_function_with_error_buffer!`.
In reality, there is no return value to be handled, so we just use `new_host_function!`.
> No return buffer when updating a BPR

- runtime/plaid/src/data/internal/mod.rs
- runtime/plaid/src/data/interval/mod.rs
Correctly handle the equality case by relying on `cmp(...)`.
> Fix Ord impl for DelayedMessage and ScheduledJob

- runtime/plaid-stl/src/plaid/cache.rs
- runtime/plaid-stl/src/plaid/storage.rs
There is a mismatch in the return values between some API functions for cache and storage insertion and their corresponding STL calls. The API functions return `i32` but the STL functions are declared with `u32`.
This PR rectifies this by using `i32` everywhere.
> Fix return value for insert functions

- runtime/plaid/src/apis/general/logback.rs
- runtime/plaid/src/apis/general/mod.rs
- runtime/plaid/src/apis/mod.rs
- runtime/plaid/src/bin/plaid.rs
- runtime/plaid/src/data/internal/mod.rs
- runtime/plaid/src/data/mod.rs
- runtime/plaid/src/storage/dynamodb/mod.rs
- runtime/plaid/src/storage/in_memory/mod.rs
- runtime/plaid/src/storage/mod.rs
- runtime/plaid/src/storage/sled/mod.rs
When it comes to logbacks, what is persisted in the DB and what is loaded in the in-memory heap is not necessarily the same. If someone were to change the content of the DB (e.g., deleting a logback entry to prevent its execution), nothing would happen until Plaid is rebooted. This feels counterintuitive and error-prone.
This PR introduces strong synchronization between DB and heap: at every iteration, the heap's content is discarded and it is refilled with the content read from the DB. This guarantees that out-of-band changes to the DB are reflected in Plaid on the next logback iteration.
However, this means logbacks now conceptually need a DB to read content from. This is at odds with the fact that Plaid can run without persistent storage.
To solve this issue, we introduce a new …
> Keep logbacks and DB in sync

- runtime/plaid/src/apis/npm/npm_web_client.rs
The issue is that, when listing npm tokens, we only got the first 10 because of pagination. This means we would fail to find a token that sits on page 2.
This PR introduces an imperfect but practical solution, by adding the query param `perPage=100`. As long as there are less than 100 npm tokens in total, we will get them all.
Then, a more long-term solution that handles pagination for an arbitrary number of tokens can be introduced.
> Fix npm list tokens

- runtime/plaid/src/data/interval/mod.rs
When generating the timing oﬀset for tasks ran on a schedule it is possible that the source of the random oﬀset will
cause the program to panic. This is due to the use of `unwrap()` in generating this random oﬀset.
While cases in which `srand.fill()` returns an error are unlikely to occur in practice, this can happen with edge cases
such as a lack of system entropy or when the code is run on a custom system.
This PR removes the `unwrap()` and, in case `srand.fill()` fails, defaults to a safe value.
> Do not use unwrap when pulling randomness for splay

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid/Cargo.toml
- runtime/plaid/src/apis/general/logback.rs
- runtime/plaid/src/apis/general/mod.rs
- runtime/plaid/src/apis/mod.rs
- runtime/plaid/src/bin/plaid.rs
Bring back the shortcut for 0-delay logbacks, so that they can be executed immediately, without passing through the storage layer.
> Bring back shortcut for 0-delay logbacks

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid-stl/src/slack/mod.rs
- runtime/plaid/Cargo.toml
- runtime/plaid/src/apis/slack/api.rs
- runtime/plaid/src/functions/api.rs
Add a new API to retrieve a user's DND info from Slack's API.
> Slack get DND

- runtime/plaid/src/data/websocket/mod.rs
If the logger used for recording system errors is not disconnected, then when a WebSocket connection error occurs,
the logger will fail to record this and return an error, which causes the WebSocket client thread to panic. This will mean
the related URI is never marked as having failed and will continue to repeat connection attempts without increasing
the back oﬀ time.
> fix(websocket): Prevent client panic on logger error

- runtime/plaid/src/data/github/mod.rs
- runtime/plaid/src/data/mod.rs
- runtime/plaid/src/data/okta/mod.rs
Avoid unwrapping and instead bubble up the error.
Note - Now the log is marked as seen only _after_ being successfully sent. This ensures that, in case of an error, a future run of the data generator will process that log and not discard it as already-seen.
> Gracefully handle errors when sending DG logs for processing

- .github/workflows/FeatureCheck.yml
- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid-stl/src/github/mod.rs
- runtime/plaid/Cargo.toml
- runtime/plaid/src/apis/github/repos.rs
- runtime/plaid/src/functions/api.rs
The API for modules will return whether a CODEOWNERS file is:
* OK - It is present and has no errors
* Missing
* Invalid - It is present but there is at least one error
> Add runtime API to check a repo's CODEOWNERS file

- modules/Cargo.lock
- modules/Cargo.toml
- modules/tests/test_vec_entrypoint/Cargo.toml
- modules/tests/test_vec_entrypoint/harness/harness.sh
- modules/tests/test_vec_entrypoint/src/lib.rs
- runtime/plaid-stl/src/lib.rs
- runtime/plaid/resources/config/apis.toml
- runtime/plaid/resources/config/loading.toml
- runtime/plaid/resources/config/webhooks.toml
- runtime/plaid/resources/docker/musl/Dockerfile.amd64
The new entrypoint preserves the `Vec<u8>` it gets from the `Message` and passes it to the `main` function, which is then responsible for handling it.
> Add new entrypoint to support raw bytes as logs

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid-stl/src/github/pull_request.rs
- runtime/plaid-stl/src/github/types.rs
- runtime/plaid/Cargo.toml
- runtime/plaid/src/apis/github/pull_requests.rs
- runtime/plaid/src/apis/github/repos.rs
- runtime/plaid/src/functions/api.rs
Modified the `create_pull_request` function to return the created pull request data instead of just indicating success. This change allows callers to access important metadata like the PR number, URL, and other details immediately after creation.
- **Runtime/STL**: Updated `create_pull_request` function signature to return `PullRequest` instead of `()`
- **Runtime/STL**: Added return buffer handling to capture and deserialize PR data from the host function
- **Runtime/API**: Modified GitHub API handler to return response body instead of status code only
- **Runtime/Functions**: Updated function macro to use `impl_new_function_with_error_buffer!` to support data return
Previously, the `create_pull_request` function only indicated whether the operation succeeded but didn't provide access to …
> Return PR data from `create_pull_request` function
