obelisk/plaid

- plaid-stl/src/github/mod.rs
- plaid/src/apis/github/pats.rs
- plaid/src/apis/github/repos.rs
- plaid/src/apis/github/teams.rs
- plaid/src/apis/github/validators.rs
- plaid/src/functions/api.rs
Implements three new APIs:
1. [Get branch protection](https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#get-branch-protection)
2. [Update branch protection](https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection)
3. [List repository collaborators](https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#list-repository-collaborators)
> Implement additional Github APIs

- plaid/resources/plaid.toml
- plaid/src/apis/general/mod.rs
- plaid/src/apis/mod.rs
- plaid/src/apis/okta/mod.rs
- plaid/src/apis/pagerduty/mod.rs
- plaid/src/apis/slack/mod.rs
- plaid/src/apis/splunk/mod.rs
- plaid/src/apis/yubikey/mod.rs
- plaid/src/data/okta/mod.rs
See https://github.com/obelisk/plaid/pull/5
> Okta tailer

- plaid/resources/Dockerfile_quorum.aarch64
Update quorum Dockerfile to include secrets
> Update quorum Dockerfile to include secrets

- plaid/src/config.rs
- plaid/src/main.rs
Adds a new field to the config to set the size of the log queue
> Configurable log queue size

- plaid/src/data/okta/mod.rs
Addresses https://github.com/obelisk/plaid/issues/13
> Make Okta limit optional

- Cargo.lock
- plaid-stl/Cargo.toml
- plaid-stl/src/github/mod.rs
- plaid/Cargo.toml
- plaid/src/apis/github/code.rs
- plaid/src/apis/github/mod.rs
- plaid/src/apis/github/repos.rs
- plaid/src/apis/github/validators.rs
- plaid/src/functions/api.rs
Add an API that allows one to search for files with a given name in GitHub. The API also supports specifying selection criteria that determine which results should be kept or discarded.
> Support searching for file in GitHub

- Cargo.lock
- plaid-stl/Cargo.toml
- plaid/Cargo.toml
- plaid/resources/Cargo.toml
Cut the build of 13.3. Also copy a new dep over to the Quorum build
> Cut 13.3; fix quorum build

- modules/tests/test_shared_db_rule_1/harness/harness.sh
- modules/tests/test_shared_db_rule_1/src/lib.rs
- modules/tests/test_shared_db_rule_2/src/lib.rs
- runtime/plaid-stl/src/lib.rs
- runtime/plaid-stl/src/plaid/storage.rs
- runtime/plaid/src/functions/api.rs
- runtime/plaid/src/functions/storage.rs
Add API to list keys from shared DB
> Add API to list keys from shared DB

- .github/workflows/Checks.yml
- testing/integration.sh
Make the CI faster by compiling different feature combinations in parallel
> Make the CI faster 

- runtime/plaid/Cargo.toml
- runtime/plaid/src/bin/sled_ddb_migrator.rs
Add tool to migrate the DB from sled to DynamoDB.
Note - The emphasis is on functionality, not on code quality aspects like error management.
> Add tool to migrate the DB from sled to DynamoDB

- runtime/Cargo.lock
- runtime/plaid-stl/src/github/mod.rs
- runtime/plaid/resources/docker/Dockerfile
- runtime/plaid/src/apis/github/repos.rs
- runtime/plaid/src/functions/api.rs
Adding support for Github API to fetch a repo's custom properties. This is useful for rules to use custom properties for filtering.
> Add Github API to fetch repository's custom properties

- runtime/plaid/src/logging/mod.rs
In some instances, the log sent to a rule is sensitive and should not be logged to external logging sources on rule execution failure. To combat this, we introduce an optional `show_log_on_error` (defaults to `true`) flag in the `LoggingConfiguration` struct. When set to `false`, the logging subsystem replaces the log sent to the rule with an empty string.
Currently, this is a global setting in the runtime and applies to all rules but could be applied at a more granular level by making `show_log_on_error` into a list of rule names
> Add `show_log_on_error` configuration flag to omit logs from logs

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid/Cargo.toml
- runtime/plaid/src/bin/db_migrator.rs
Take into account that old logbacks might miss logback_allowed.
> Update DB migrator

- modules/tests/test_db/harness/harness.sh
- runtime/plaid/src/config.rs
* Add an additional, multi-byte DB test case
* Update the default value of the secret file to be a TOML file and no longer a JSON file.
> Update default value of secrets file and improve test

- runtime/plaid/Cargo.toml
- runtime/plaid/src/bin/ddb_logback_explorer.rs
- runtime/plaid/src/data/internal/mod.rs
Allows for listing logbacks in DynamoDB and filtering by
* log type (exact match)
* log source (substring)
* log data (substring)
> Add CLI for exploring logbacks

- runtime/plaid-stl/src/github/mod.rs
When making paginated requests, there is often no need to see an empty page to realize we have retrieved all values. Often, the last page won't be full, so we can stop immediately and save one extra API call.
It might not be much, but for request-intensive rules everything matters.
> Make GH code search slightly more efficient

- runtime/plaid/src/data/internal/mod.rs
Delayed messages can fail to be broadcast and as they have already been deleted from the list of pending delayed messages, this will lead to them not being transmitted.
With this PR, we delete a logback from the storage only after the `send()` method has been called successfully.
> Fix early deletion of logbacks

- runtime/plaid/src/apis/npm/npm_web_client.rs
This PR provides a proper solution to the issue that had been temporarily fixed in https://github.com/obelisk/plaid/pull/166.
Now we support paginated responses when listing npm tokens, in a similar fashion to what we do for other paginated results returned by the npm website.
> Support pagination when listing npm tokens

- runtime/plaid-stl/src/github/mod.rs
- runtime/plaid/src/apis/github/teams.rs
- runtime/plaid/src/functions/api.rs
Add APIs to add/remove repos to/from GH teams.
> Add APIs to add/remove repos to/from GH teams

- modules/Cargo.lock
- runtime/Cargo.lock
- runtime/plaid-stl/Cargo.toml
- runtime/plaid-stl/src/github/mod.rs
- runtime/plaid/Cargo.toml
- runtime/plaid/src/apis/github/repos.rs
Add debug logs to CODEOWNERS API
> Add debug logs to CODEOWNERS API
